Repository SatelCreative/spylib, pull requests merged in 2022-08, with the labels that each got.

#161 ✨ Add new pr-title-checker
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-checker.yml
Labels: Type: DevOps

#167 🐛 Fix fastapi tests
  pyproject.toml
  tests/oauth/test_base.py
  tests/test_session_token.py
Labels: Type: Bug, Type: DevOps

#168 🎨 add bytes type data support to webhook hmac validate function
  spylib/constants.py
  spylib/webhook/__init__.py
  tests/test_webhook_verification.py
Labels: Type: Enhancement
