Repository SatelCreative/spylib, pull requests merged in 2022-03, with the labels that each got.

#88 📝 Reorganize the documentation in sections
  README.md
  docs/admin-api.md
  docs/api_version.md
  docs/development-contributing.md
  docs/index.md
  docs/oauth.md
  docs/session-token.md
  docs/webhooks.md
Labels: Type: Documentation, Priority: Medium

#85 Fix/dependency versions
  .github/workflows/tests.yml
  .gitignore
  poetry.lock
  pyproject.toml
Labels: Type: Enhancement

#99 Miscellaneous documentation improvements
  .gitignore
  CHANGELOG.md
  CODEOWNERS
  CONTRIBUTING.md
  docs/admin-api.md
  docs/development-contributing.md
  mkdocs.yml
Labels: Type: Documentation, Priority: Medium

#98 :bug: Fix tests to prevent pytest from hanging
  pyproject.toml
  tests/conftest.py
Labels: Type: Bug, Priority: Medium

#82 Add path_prefix param to init oauth router and url
  docs/oauth.md
  spylib/oauth/redirects.py
  spylib/oauth/router.py
Labels: Type: Bug, Type: Enhancement

#102 Release/0.5.0
  CHANGELOG.md
  pyproject.toml
  spylib/__init__.py
Labels: Priority: Medium

#101 Make fastapi optional and raise error when imported but not installed
  pyproject.toml
  setup.cfg
  spylib/exceptions.py
  spylib/oauth/router.py
  tests/oauth/test_base.py
  tests/utils/test_session_token.py
  tox.ini
Labels: Type: Enhancement

#104 Fix/replace shortuuid dependency with code
  pyproject.toml
  spylib/utils/misc.py
  spylib/utils/shortuuid.py
  tests/utils/test_shortuuid.py
Labels: Type: Enhancement

#108 ✨ Enforce gitmoji in PR title
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-checker.yml
Labels: Type: Enhancement, Type: DevOps
