Repository SatelCreative/spylib, pull requests merged in 2023-07, with the labels that each got.

#195 🚀 Upgrade tox to v4
  .github/workflows/compare.yml
  .github/workflows/docs.yml
  .github/workflows/tests.yml
  tox.ini
Labels: Type: DevOps

#196 :memo: Fix the link to point to the latest docs
  CONTRIBUTING.md
Labels: Priority: Medium

#197 ⬆️ ➖ Update package dependencies
  pyproject.toml
  spylib/exceptions.py
  spylib/hmac.py
  tests/admin_api/test_graphql_operation_names.py
  tests/admin_api/test_initialization.py
  tests/conftest.py
  tests/fastapi_extensions/conftest.py
  tests/oauth/test_base.py
  tests/test_hmac.py
  tests/test_session_token.py
Labels: Type: Dependencies

#198 👷 add python 3.11 to tox test suite
  .github/workflows/tests.yml
  tox.ini
Labels: Type: DevOps, Type: Dependencies
